project_id = "tkshatphagquissyykvc"

[auth]
site_url = "env(SITE_URL)"
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
otp_length = 6
otp_expiry = 3600

[auth.email.template.magic_link]
subject = "Your Training Hub Login Code"
content_path = "./supabase/templates/magic_link.html"
