project_id = "tkshatphagquissyykvc"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.export-data]
verify_jwt = false

[functions.calendar-feed]
verify_jwt = false
